import { createFileRoute, Link } from "@tanstack/react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Mail, ClipboardList, CalendarClock, BookOpenText, MessageCircle, Snowflake, ArrowRight } from "lucide-react";

export const Route = createFileRoute("/_authenticated/dashboard")({
  component: Dashboard,
});

const tools = [
  { to: "/email", icon: Mail, title: "Smart Email Generator", desc: "Polished emails for any audience and tone." },
  { to: "/summarizer", icon: ClipboardList, title: "Meeting Notes Summarizer", desc: "Extract decisions, owners, and deadlines." },
  { to: "/planner", icon: CalendarClock, title: "AI Task Planner", desc: "Eisenhower matrix and time-blocked schedules." },
  { to: "/research", icon: BookOpenText, title: "Research Assistant", desc: "Distill articles into clear insights." },
  { to: "/chat", icon: MessageCircle, title: "AI Chat", desc: "Ask anything about your workday." },
] as const;

function Dashboard() {
  return (
    <div className="mx-auto max-w-6xl space-y-8 p-6 md:p-10">
      <div className="flex items-start gap-4">
        <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-primary shadow-glow">
          <Snowflake className="h-6 w-6 text-primary-foreground" />
        </div>
        <div>
          <h1 className="font-display text-3xl font-bold tracking-tight">Welcome to <span className="text-gradient">Snow Flow AI</span></h1>
          <p className="text-muted-foreground">Your AI-powered workplace assistant. Pick a tool to get started.</p>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link key={t.to} to={t.to} className="group">
            <Card className="h-full shadow-card transition hover:border-primary/60 hover:shadow-glow">
              <CardHeader>
                <div className="mb-2 flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-primary shadow-glow">
                  <t.icon className="h-5 w-5 text-primary-foreground" />
                </div>
                <CardTitle className="flex items-center justify-between">
                  {t.title}
                  <ArrowRight className="h-4 w-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-primary" />
                </CardTitle>
                <CardDescription>{t.desc}</CardDescription>
              </CardHeader>
            </Card>
          </Link>
        ))}
      </div>

      <div className="rounded-2xl border border-border bg-card/60 p-6 text-sm text-muted-foreground backdrop-blur">
        <p><strong className="text-foreground">Responsible AI:</strong> All outputs are generated by AI and should be reviewed for accuracy and suitability before professional use. Snow Flow AI will indicate when information needs verification rather than make assumptions.</p>
      </div>
    </div>
  );
}
